version: '3.8'
# TODO: BBMRI expects Traefik to already exist
services:
  traefik:
    image: traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # - --providers.file.directory=/conf/
      - --accesslog=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik-forward-auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${OAUTH_ISSUER_URL}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${AUTHENTICATION_SECRET}
      - OAUTH2_PROXY_COOKIE_DOMAINS=.${GUI_HOST}
      - OAUTH2_PROXY_HTTP_ADDRESS=:4180
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.${GUI_HOST}
      - OAUTH2_PROXY_UPSTREAMS=static://202
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_ALLOWED_GROUPS=${ALLOWED_GROUPS}
      # For some reason, login.verbis.dkfz.de does not have a "groups" scope but this comes automatically through a
      # scope called microprofile-jwt. Remove the following line once we have a "groups" scope.
      - OAUTH2_PROXY_SCOPE=openid profile email
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4180"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4180"
      - "traefik.http.routers.oauth2.rule=(Host(`${GUI_HOST}`) || Host(`backend.${GUI_HOST}`)) && PathPrefix(`/oauth2/`)"
      - "traefik.http.routers.oauth2.tls=true"

  lens-web-components:
    image: lens-web-components
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lens.rule=Host(`${GUI_HOST}`)"
      - "traefik.http.routers.lens.tls=true"
      - "traefik.http.routers.lens.middlewares=traefik-forward-auth"

  spot:
    image: docker.verbis.dkfz.de/ccp-private/central-spot
    ports:
      - 8080:8080
    environment:
      BEAM_SECRET: "${LOCAL_BEAM_SECRET}"
      BEAM_URL: http://beam-proxy:8081
      BEAM_PROXY_ID: ${LOCAL_BEAM_ID}
      BEAM_BROKER_ID: ${BROKER_HOST}
      # TODO: Implement Switch between spot and focus
      BEAM_APP_ID: "focus"
    depends_on:
      - "beam-proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.spot.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolalloworiginlist=https://${GUI_HOST}"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolmaxage=-1"
      - "traefik.http.routers.spot.rule=Host(`backend.${GUI_HOST}`)"
      - "traefik.http.routers.spot.tls=true"
      - "traefik.http.routers.spot.middlewares=corsheaders,traefik-forward-auth"

  beam-proxy:
    image: docker.verbis.dkfz.de/cache/samply/beam-proxy:develop
    environment:
      BROKER_URL: https://${BROKER_HOST}
      PROXY_ID: ${LOCAL_BEAM_ID}.${BROKER_HOST}
      # TODO: Same for focus here
      APP_focus_KEY: ${LOCAL_BEAM_SECRET}
      PRIVKEY_FILE: /run/secrets/proxy.pem
      ALL_PROXY: ${http_proxy}
    secrets:
      - proxy.pem
      - root.crt.pem

  ## Only use this for test purposes
  blaze:
    image: samply/blaze:develop
    ports:
     - "8082:8080"
    profiles: ["development"]

  test-data-loader:
    image: samply/test-data-loader
    environment:
      FHIR_STORE_URL: "http://blaze:8080/fhir"
      PATIENT_COUNT: "2000"
    command: sh -c "sleep 60 && /app/run.sh"
    profiles: ["development"]

  project-manager:
    image: samply/project-manager:develop
    ports:
      - 8097:8097
    # environment:
    #   OIDC_CLIENT_ID: ${PROJECT_MANAGER_OAUTH_CLIENT_ID}
    #   OIDC_CLIENT_SECRET: ${PROJECT_MANAGER_OAUTH_CLIENT_SECRET}
    #   OIDC_REALM: ${PROJECT_MANAGER_OAUTH_CLIENT_REALM}
    #   OIDC_URL: ${PROJECT_MANAGER_OAUTH_ISSUER_URL}
    env_file:
      - env/project-manager.env
    volumes:
      - "./templates:/templates"
      - "./documents:/documents"
      - "./public-documents:/public-documents"

  project-manager-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

secrets:
  proxy.pem:
    # TODO: Key in BBMRI was directly stored in lens directory!
    file: /etc/lens/pki/${LOCAL_BEAM_ID}.priv.pem
  root.crt.pem:
    file: ./rootcerts/${BROKER_HOST}-root.crt.pem
